### ISSUE TITLE
Allow user to register and sign into app

### ISSUE THREAD

**Issue by calebwagner** [calebwagner/uteach-ilearn-client#1]
**TODO:**

- [ ] create login.js file that handles logic for login page
- [ ] create register.js file that handles logic for register page
- [ ] set up logic for App views in `App.js`
