### ISSUE TITLE
Get all posts on home page

### ISSUE THREAD

**Issue by calebwagner** [calebwagner/uteach-ilearn-client#2]
When a user sings in they should see all posts. They have the option to click "post" button to create a post.

**TODO:**

- [ ] create `PostProvider.js` function that gets all posts
- [ ] create `PostList.js` that renders all posts
- [ ] create `PostDetail.js` that displays layout of posts
- [ ] import modules to `ApplicationViews.js` and set up routes
