### ISSUE TITLE
Create Aside 

### ISSUE THREAD

**Issue by calebwagner** [calebwagner/uteach-ilearn-client#4]
**TODO:**

- [ ] create a "teach me" link that directs the user to the home page
- [ ] create a link "categories" that directs the user to the categories page
- [ ] create a "messages" link that directs the user to the messages page
- [ ] create a "profile" link that directs the user to the current users profile page
